services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config.celery_app:app worker -l info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=${CELERY_BROKER_URL_DOCKER}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND_DOCKER}
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A config.celery_app:app beat -l info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=${CELERY_BROKER_URL_DOCKER}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND_DOCKER}
    env_file:
      - .env
    depends_on:
      - redis
